apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ak-cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      publicKeyPath: mykey1111

nodeGroups:
  - name: ng-2
    minSize: 1
    maxSize: 4
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.micro"] 
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
      ssh:
        publicKeyPath: mykey1111