apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
- name: mysqluser-pass
  literals:
  - password1=redhat
resources:
  - mysql_deploy.yml
  - nextcloud_deploy.yml